// Tabelle Liefereinheit
CREATE TABLE LIEFEREINHEIT 
	(
	   	ID 			NUMBER(10,0)	NOT NULL PRIMARY KEY,
	   	NAME		NVARCHAR2(255)	NOT NULL, 
		BFSNR		NUMBER(10,0), 
		GPR_SOURCE	NVARCHAR2(512),
		TS_SOURCE	NVARCHAR2(512), 
		MD5			VARCHAR2(36 BYTE),
		GPRCODE		NVARCHAR2(8)
  	);

// Tabelle Ticket
CREATE TABLE TICKET 
  	(
	  	ID				NVARCHAR2(10) NOT NULL PRIMARY KEY, 
		LIEFEREINHEIT 	NUMBER(10,0) REFERENCES LIEFEREINHEIT(ID), 
		STATUS			NUMBER(2,0) NOT NULL,
		ART				NUMBER(2,0) NOT NULL,
		TASK_ID_GEODB	NUMBER(38,0)
	);